# Generated by Django 2.1.7 on 2020-07-28 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionsale',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionsale',
            name='foodgrain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.FoodGrain'),
        ),
        migrations.AddField(
            model_name='transactionsale',
            name='produce',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.Produce'),
        ),
        migrations.AddField(
            model_name='transactionsale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_seller', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transactionsale',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Warehouse'),
        ),
        migrations.AddField(
            model_name='storagetransaction',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storagetransaction',
            name='produce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Produce'),
        ),
        migrations.AddField(
            model_name='storagetransaction',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Warehouse'),
        ),
        migrations.AddField(
            model_name='produce',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produce',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to='user.Location'),
        ),
        migrations.AddField(
            model_name='produce',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produce', to='user.FoodGrain'),
        ),
        migrations.AddField(
            model_name='placebid',
            name='bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.Bid'),
        ),
        migrations.AddField(
            model_name='placebid',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryservice',
            name='branches',
            field=models.ManyToManyField(related_name='branches', to='user.Location'),
        ),
        migrations.AddField(
            model_name='deliveryservice',
            name='cur_loc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cur_loc', to='user.Location'),
        ),
        migrations.AddField(
            model_name='deliveryservice',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.DeliveryService'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.TransactionSale'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='order_storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.StorageTransaction'),
        ),
        migrations.AddField(
            model_name='bid',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bid',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.FoodGrain'),
        ),
    ]
